#!/bin/bash
# Plugin Health Monitor
# Checks all ubiquity-os-marketplace plugin repos for consecutive workflow failures.
# If 10+ consecutive failures found, posts a notification comment.

set -euo pipefail

ORG="ubiquity-os-marketplace"
NOTIFICATION_REPO="ubiquity-os/.github"
NOTIFICATION_ISSUE="12"
FAILURE_THRESHOLD=10
RECENT_RUNS=15

echo "=== Plugin Health Monitor ==="
echo "Organization: $ORG"
echo "Failure threshold: $FAILURE_THRESHOLD consecutive failures"
echo "Checking last $RECENT_RUNS runs per repo"
echo ""

# Get all plugin repos (with pagination)
repos=""
page=1
while true; do
  page_repos=$(gh api "orgs/$ORG/repos?per_page=100&sort=updated&page=$page" --jq '.[].name' 2>/dev/null || true)
  [ -z "$page_repos" ] && break
  repos="$repos $page_repos"
  count=$(echo "$page_repos" | wc -l)
  [ "$count" -lt 100 ] && break
  page=$((page + 1))
done
repos=$(echo $repos | xargs)

failed_repos=()

for repo in $repos; do
  echo "Checking $repo..."

  # Get recent completed workflow runs to count consecutive failures
  runs=$(gh api "repos/$ORG/$repo/actions/runs?per_page=$RECENT_RUNS&status=completed" --jq '.workflow_runs[].conclusion' 2>/dev/null || true)

  if [ -z "$runs" ]; then
    echo "  ✅ No runs found"
    continue
  fi

  # Count consecutive failures (most recent first)
  consecutive_failures=0

  for conclusion in $runs; do
    if [ "$conclusion" = "failure" ]; then
      consecutive_failures=$((consecutive_failures + 1))
    else
      break
    fi
  done

  if [ "$consecutive_failures" -ge "$FAILURE_THRESHOLD" ]; then
    echo "  🚨 $consecutive_failures consecutive failures!"
    failed_repos+=("$repo:$consecutive_failures")
  else
    echo "  ✅ $consecutive_failures consecutive failures (below threshold)"
  fi
done

echo ""
echo "=== Summary ==="

if [ ${#failed_repos[@]} -eq 0 ]; then
  echo "All plugins healthy! No action needed."
  exit 0
fi

# Build notification message
message="## 🚨 Plugin Health Alert ($(date -u +%Y-%m-%d))

The following plugins have **$FAILURE_THRESHOLD+ consecutive workflow failures**:

"
for entry in "${failed_repos[@]}"; do
  repo="${entry%%:*}"
  count="${entry##*:}"
  message+="| Plugin | Consecutive Failures | Latest Runs |
|--------|----------------------|-------------|
| [$repo](https://github.com/$ORG/$repo/actions) | $count | [View](https://github.com/$ORG/$repo/actions) |

"
done

message+="**Total affected: ${#failed_repos[@]} plugins**

cc @0x4007 @gentlementlegen

---
*Generated by [Plugin Health Monitor](https://github.com/$ORG/.github) cron job*"

echo "$message"
echo ""
echo "Posting notification to $NOTIFICATION_REPO#$NOTIFICATION_ISSUE..."

gh issue comment "$NOTIFICATION_ISSUE" \
  --repo "$NOTIFICATION_REPO" \
  --body "$message"

echo "✅ Notification posted."
