#!/bin/bash
# Plugin Health Monitor v2
# Checks all ubiquity-os-marketplace plugin repos for consecutive workflow failures.
# If 10+ consecutive failures found, posts a notification comment.

set -eo pipefail

ORG="ubiquity-os-marketplace"
NOTIFICATION_REPO="ubiquity-os/.github"
NOTIFICATION_ISSUE="12"
FAILURE_THRESHOLD=10
RECENT_RUNS=15

echo "=== Plugin Health Monitor ==="
echo "Organization: $ORG"
echo "Failure threshold: $FAILURE_THRESHOLD consecutive failures"
echo "Checking last $RECENT_RUNS runs per repo"
echo ""

# Get all plugin repos (all statuses to detect streak breaks)
repos=$(gh api "orgs/$ORG/repos?per_page=100&sort=updated" --jq '.[].name' 2>/dev/null || echo "")

if [ -z "$repos" ]; then
  echo "Failed to fetch repos. Exiting."
  exit 1
fi

failed_repos=()

for repo in $repos; do
  echo "Checking $repo..."

  # Get recent workflow runs with conclusion (all statuses, not just failures)
  # This lets us properly detect when a streak of failures is broken
  runs_data=$(gh api "repos/$ORG/$repo/actions/runs?per_page=$RECENT_RUNS" --jq '.workflow_runs[] | "\(.conclusion)"' 2>/dev/null || true)

  if [ -z "$runs_data" ]; then
    echo "  ✅ No workflow runs found"
    continue
  fi

  # Count consecutive failures (most recent first)
  consecutive_failures=0
  while IFS= read -r conclusion; do
    if [ "$conclusion" = "failure" ]; then
      consecutive_failures=$((consecutive_failures + 1))
    else
      break
    fi
  done <<< "$runs_data"

  if [ "$consecutive_failures" -ge "$FAILURE_THRESHOLD" ]; then
    echo "  🚨 $consecutive_failures consecutive failures!"
    failed_repos+=("$repo:$consecutive_failures")
  else
    echo "  ✅ $consecutive_failures consecutive failures (below threshold)"
  fi
done

echo ""
echo "=== Summary ==="

if [ ${#failed_repos[@]} -eq 0 ]; then
  echo "All plugins healthy! No action needed."
  exit 0
fi

# Build notification message (single table)
message="## 🚨 Plugin Health Alert ($(date -u +%Y-%m-%d))

The following plugins have **${FAILURE_THRESHOLD}+ consecutive workflow failures**:

| Plugin | Consecutive Failures | Actions |
|--------|----------------------|---------|"

for entry in "${failed_repos[@]}"; do
  repo="${entry%%:*}"
  count="${entry##*:}"
  message+="
| [$repo](https://github.com/$ORG/$repo/actions) | $count | [View](https://github.com/$ORG/$repo/actions) |"
done

message+="

**Total affected: ${#failed_repos[@]} plugins**

cc @0x4007 @gentlementlegen

---
*Generated by [Plugin Health Monitor](https://github.com/$ORG/.github) cron job*"

echo "$message"
echo ""
echo "Posting notification to $NOTIFICATION_REPO#$NOTIFICATION_ISSUE..."

gh issue comment "$NOTIFICATION_ISSUE" \
  --repo "$NOTIFICATION_REPO" \
  --body "$message"

echo "✅ Notification posted."
